language: python

matrix:
  include:
    - python: 3.7
      script: tox -e py37
    - python: 3.7
      arch: arm64
      script: tox -e py37
    - python: 3.8
      script: tox -e py38
    - python: 3.8
      arch: arm64
      script: tox -e py38

before_install:
  - sudo apt-get install -y python-dev gcc

install:
  - pip install cython tox codecov
  - uname -m

script:
  - tox -e py

after_success:
  - cd tests && codecov
